### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Idkwhome69** [SSujitX/facebook-pages-scraper#1]
How to use this please help me with it? I don't know anything about coding tbh💀 I've installed it but I don't know how to use it please help me.

**Comment by SSujitX** [comment]
> How to use this please help me with it? I don't know anything about coding tbh💀 I've installed it but I don't know how to use it please help me.

Step 1: Install VS Code
Download VS Code:
[VS Code Download](https://code.visualstudio.com/Download)
Install it:
Windows: Run the .exe file.
Mac: Open the .dmg file and drag VS Code to the Applications folder.
Step 2: Install Python
Download Python:

[Python Download](https://www.python.org/downloads/)
Install Python:

Windows:
During installation, make sure to check "Add Python to PATH".
Mac: Python comes pre-installed, but update it if needed via the download.
Verify Installation: Open a terminal and run:

bash
Copy code
python --version
pip --version
Step 3: Install the Python Extension in VS Code
Open VS Code.
On the left sidebar, click on the Extensions icon (or press Ctrl + Shift + X / Cmd + Shift + X on Mac).
In the search bar, type Python and click Install on the official Python extension (by Microsoft).
Step 4: Configure Python in VS Code
Open the Command Palette (press Ctrl + Shift + P / Cmd + Shift + P on Mac).
Type Python: Select Interpreter and hit Enter.
Choose the installed Python version from the list.
If you don’t see it, click Enter Interpreter Path > Find and locate your Python installation.
Step 5: Install the facebook-pages-scraper Package
Open the terminal in VS Code:
Press Ctrl + ~ (or Cmd + ~ on Mac).
Install the package:
bash
Copy code
pip install facebook-pages-scraper
Optional: Install rich for better output:
bash
Copy code
pip install rich
Step 6: Create and Run Your Script
Create a new file in VS Code:

Click File > New File, save it as scraper.py.
Copy this code:

python
Copy code
from facebook_page_scraper import FacebookPageScraper
from rich import print

def main():
    urls = [
        "/instagram",
        "https://www.facebook.com/facebook",
        "https://www.facebook.com/MadKingXGaming/",
        "https://www.facebook.com/LinkedIn",
    ]

    for url in urls:
        print(f">= Scraping URL/Username: {url}\n")

        page_info = FacebookPageScraper.PageInfo(url)
        print("Page Information:")
        print(page_info)
        print("\n" + "=" * 80 + "\n")

if __name__ == "__main__":
    main()
Run it in the terminal:

bash
Copy code
python scraper.py
You’re Set!
Everything should work now. If you hit any errors, drop them here, and I’ll guide you through it. 💀

**Comment by Idkwhome69** [comment]
Sir thank you so much for the detailed help appreciate your kindness and efforts but I need help with the step 6.. Created a file copied the code but where do I paste it and where do I add the facebook user url? Please help almost there😅
