### ISSUE TITLE
Facebook blocks data collection after some time

### ISSUE THREAD

**Issue by 1000001ndrey1010100** [SSujitX/facebook-pages-scraper#2]
Hello,

First of all, thank you for providing this great Facebook scraping tool! I have been using it successfully, but I am facing a problem when sending requests after a while. After a while, Facebook stops providing data and asks for login instead.

I would like to ask for your advice on the best methods to solve this problem. Specifically:

Delay between requests:

Should I introduce a delay between requests to reduce the chance of being blocked?
If so, what delay range would you recommend?
Request Rate Limit:

Is there a known maximum number of requests per minute/hour that Facebook allows before blocking mechanisms are triggered?
If this limit is exceeded, how should the scraper handle the situation?
Alternative Strategies:

Are there other strategies or settings (such as using certain headers, rotating user agents, or setting cookies) that can help circumvent this problem?
I would really appreciate any recommendations or guidance you can provide to ensure stable scraping without triggering Facebook's anti-parsing mechanisms.

Thanks in advance for your help!

**Comment by SSujitX** [comment]
> Hello,
> 
> First of all, thank you for providing this great Facebook scraping tool! I have been using it successfully, but I am facing a problem when sending requests after a while. After a while, Facebook stops providing data and asks for login instead.
> 
> I would like to ask for your advice on the best methods to solve this problem. Specifically:
> 
> Delay between requests:
> 
> Should I introduce a delay between requests to reduce the chance of being blocked? If so, what delay range would you recommend? Request Rate Limit:
> 
> Is there a known maximum number of requests per minute/hour that Facebook allows before blocking mechanisms are triggered? If this limit is exceeded, how should the scraper handle the situation? Alternative Strategies:
> 
> Are there other strategies or settings (such as using certain headers, rotating user agents, or setting cookies) that can help circumvent this problem? I would really appreciate any recommendations or guidance you can provide to ensure stable scraping without triggering Facebook's anti-parsing mechanisms.
> 
> Thanks in advance for your help!

Can you tell me, after how many requests this login appears? Also, give me the list of pages. i want to test it myself.

**Comment by 1000001ndrey1010100** [comment]
> > Hello,
> > First of all, thank you for providing this great Facebook scraping tool! I have been using it successfully, but I am facing a problem when sending requests after a while. After a while, Facebook stops providing data and asks for login instead.
> > I would like to ask for your advice on the best methods to solve this problem. Specifically:
> > Delay between requests:
> > Should I introduce a delay between requests to reduce the chance of being blocked? If so, what delay range would you recommend? Request Rate Limit:
> > Is there a known maximum number of requests per minute/hour that Facebook allows before blocking mechanisms are triggered? If this limit is exceeded, how should the scraper handle the situation? Alternative Strategies:
> > Are there other strategies or settings (such as using certain headers, rotating user agents, or setting cookies) that can help circumvent this problem? I would really appreciate any recommendations or guidance you can provide to ensure stable scraping without triggering Facebook's anti-parsing mechanisms.
> > Thanks in advance for your help!
> 
> Can you tell me, after how many requests this login appears? Also, give me the list of pages. i want to test it myself.

First of all, I want to apologize for the confusion. After testing, I can confirm that your tool works flawlessly when used with a real residential IP address. I successfully processed 3024 Facebook links without encountering any issues related to login requests or failed requests.

The issue was caused by using data center proxies. While testing with data center proxies, I started encountering errors as early as the 16th link in my dataset. Specifically, I received the following error:

Page Load Error [16/3024] [https://www.facebook.com/LaBellaMarket]: HTTP Error 429
This strongly suggests that the limitation is not related to your tool, but to the quality and type of proxy server used. Data center proxies seem to be quickly flagged by Facebook, resulting in rate throttling and access restrictions.

Thank you for developing such a reliable tool and I appreciate your efforts in maintaining it.
